name: Validate test plans

on:
  pull_request:

jobs:
  validate-test-plans:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate test plans
        run: npm run create-all-tests -- --validate --verbose

  validate-test-plans-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate test plans
        run: npm run create-all-tests -- --validate --verbose
